project_id = "spmdrysnmfjsfiqnltfa"

[functions.suno-add-instrumental]
verify_jwt = false

[functions.suno-callback]
verify_jwt = false

[functions.suno-check-status]
verify_jwt = false

[functions.merge-and-generate]
verify_jwt = false

[functions.musicgen-remixer]
verify_jwt = false

[functions.master-audio]
verify_jwt = false

[functions.denoise-singing]
verify_jwt = false

[functions.autotune-vocals]
verify_jwt = false

[functions.dry-recording-mix]
verify_jwt = false

[functions.kits-vocal-cleanup]
verify_jwt = false

[functions.roex-mix-master]
verify_jwt = false

[functions.roex-webhook]
verify_jwt = false